questions:
  response_id: "Response ID"
  name: "Full name"
  email: "Email address"
  on_behalf_of_org: "Are you answering this questionnaire on behalf of an organisation?"
  org_name: "What is the name of the organisation?"
  org_sector: "What sector does the organisation belong to?"
  org_other_sector: "If you selected ‘Other’, please provide your organisation’s sector below"
  frequency_of_use: "In the last 12 months, approximately how often have you used or referred to statistics from the ONS?"
  use_case: "What do you currently use the ONS’s population and migration statistics for?"
  use_case_other: "What do you currently use the ONS’s population and migration statistics for? OTHER"
  how_used: "Please explain how you currently use the ONS's population and migration statistics?"
  level_needs_met: "To what extent do these proposals meet your needs?"
  needs_better_met: "Are your current information needs better met by these proposals?"
  which_better_met: "Which of your information needs are better met by these proposals? Please explain the reasons for your answer"
  something_new: "Would these proposals allow you to do anything new that you have not previously been able to do?"
  something_new_reasons: "Do anything new... Please explain the reasons for your answer"
  needs_not_met: "Which of your current needs would not be met by these proposals? Please include reasons for your answer. For example, information around?levels of detail, accuracy, timeliness or geography"
  geographic_needs_met: "Do the proposed levels of geographic breakdown meet your information needs?"
  additional_geo_needs: "What additional geographic breakdowns would you need? Please explain the reasons for your answer."
  detail_needs_met: "Would this change in available detail still meet your needs?"
  impact_of_detail_changes: "What impact would this change in available detail have on your use of our population and migration statistics? Please explain your answer"
  need_other_definitions: "Do you need definitions for population and migration estimates other than ‘usual resident’?"
  current_interests: "For population present estimates, what is of interest to you? Please select all that apply and explain the reason for needing each definition."
  current_interest_reason: "Please explain why you need this definition of 'population present'"
  other_definitions: "What, if any, other definitions could we use to estimate population and migration that would better meet your needs?"
  frequency_needs: "For the usual resident population how frequently would you like population estimates?"
  frequency_needs_other: "If you ticked ‘Other’, please specify"
  frequency_needs_reason: "Please explain the reasons for your selected frequency and how it would meet your needs."
  timeliness_needs: "How timely would you like population estimates to be?"
  timeliness_reason: "Please explain the reason for your answer."
  preservation_needs: "What details from population and social characteristics data do you see as being important to be preserved for future generations, if any? Please explain why this data is important to be preserved."
  other_comments:  "Is there anything else about the population and migration statistics proposal that you wish to add to your response?"
  geographies_used:  "Which of these geographies do you mainly use ONS population statistics for? If you use more than one, please select all that apply"

questions_to_interpret:
  - 12
 # - 14
 # - 16
 # - 19
 # - 21
 # - 24
 # - 28
 # - 30
 # - 31
 # - 32
